### PR TITLE
fix: resolve esm and cjs issue

### PR DESCRIPTION
**Pull request by oceanroleplay**
**Please describe the changes this PR makes and why it should be merged:**

esm issue raised in #227 and later fixed in #229 but unfortunately the change applied to cjs (#231) as well, tsup banner solution does not provide any configuration that we can use atm. This PR is solution to resolve this problem with custom script.

### CODE REVIEW

**Comment by oceanroleplay** [comment]
there is one more reason, why we could not use banner. The `import.meta.url` resolved at build time. Which is not a ideal solution.

screenshot of present build output
image

**Comment by oceanroleplay** [comment]
ESM Test Result
image

note: cjs tests are not required.

**Comment by oceanroleplay** [comment]
image

@iCrawl

**Comment by oceanroleplay** [comment]
my bad sorry

**Comment by oceanroleplay** [comment]
no it's not

**Comment by iCrawl** [comment]
Oh, I see, it's the resolve at build time.

**Comment by oceanroleplay** [comment]
@iCrawl I am not sure, but please resolve this.

image

in node module, the package is updated and I can verify with package.json version. But with `generateDependencyReport()` is shows 0.7.3 and your changes are there as well.

image


but still issue is not resolved with ESM.

**Comment by iCrawl** [comment]
Lets try again in 0.7.5 🙃

**Comment by vijayymmeena** [comment]
> Lets try again in 0.7.5 🙃

well that's the solution given in this PR, so no doubt it will work. 

ref: https://github.com/discordjs/voice/commit/644af9579f02724c489514f482640b8413d2c305

**Comment by iCrawl** [comment]
Yeah I just didn't want to bring in another dependency for something so simple.

**Comment by vijayymmeena** [comment]
> Yeah I just didn't want to bring in another dependency for something so simple.

yes, I just didn't think about fs in first place, my bad. Anyway, thanks.

**Pull request closed without merging**
