### PR TITLE
Update defer to deferReply

### PR DESCRIPTION
**Pull request by slienlaffa**
function defer() doesn't work so must be updated to deferReply()

### CODE REVIEW

**Comment by Megatank58** [comment]
This has already been fixed in #174

**Comment by slienlaffa** [comment]
but it's not been merged yet

**Comment by Megatank58** [comment]
> but it's not been merged yet

But the change has already been made so this pr is considered as a duplicate, if you want to suggest something please suggest on that pr itself

**Comment by slienlaffa** [comment]
well then

**Pull request closed without merging**
