### PR TITLE
FFMPEG In-built Support

### LINKED ISSUE #143: FFmpeg custom arguments
If you'd like to pass custom FFmpeg arguments, you need to create your own FFmpeg transcoder stream. This can be annoying, especially for those who would like to use reconnect arguments (see #117 and #141)

There should be a way for users to override the FFmpeg arguments provided by the library. This could also be a more general issue of allowing users to customise the transformer graph themselves.

This isn't a simple fix and will require a bit of thinking to come up with a nice solution.

### PR DESCRIPTION
**Pull request by killer069**
**Please describe the changes this PR makes and why it should be merged:**

Added in-built support for FFMPEG without disturbing createAudioResource function.

Created a whole new function in audio - resource file. [ createFFMPEGResource() ]

**Status and versioning classification:**

Resolves #143 , #117 , #141 , #124.

### CODE REVIEW

**Review by amishshah — CHANGES_REQUESTED** [review]
I think I'm generally happy with this PR - I like how it doesn't interfere with existing code and instead builds on top as a utility.

However, two thoughts:

1. It seemingly only support Ogg opus output from FFmpeg (not all FFmpeg instances will support this, or for users that want inline volume, this is unnecessary)
2. No tests - if you could add tests that would be good, otherwise if you really do not want to I can add them once the PR is ready, but either way I think we should have tests here before merging.

Would appreciate if you could figure out a nice way of deciding whether to use Opus or PCM output here, maybe using the existing logic to help decide this

**Review by killer069 — COMMENTED** [review]
I have done everything. It would be great if you make test files and check it's actual use.

**Review by DevAndromeda — COMMENTED** [review]
🤔 imo options like `reconnect`, `reconnect_time`, `seek` should be handled by the users since this api provides `arguments` option? Users should have full control over this 😕

**Comment by killer069** [comment]
> 🤔 imo options like `reconnect`, `reconnect_time`, `seek` should be handled by the users since this api provides `arguments` option? Users should have full control over this 😕

I know about this. 

Options like `reconnect`, `reconnect_time`, `seek` are for those users who particularly don't know much about setting up FFMPEG args.

It will be easier for people who have just shifted from discord voice old module to find `seek` option. Moreover, FFMPEG has some issues with connection drops. So I added `reconnect` args only to help to fix that issue.

`arguments` allow users to have full control what they need to pass and what not to pass. [ without options like `reconnect`, `reconnect_time`, `seek` ]

**Review by killer069 — COMMENTED** [review]
Tests have been added. I have included only 2 tests since FFMPEG either convert it to OPUS or PCM according to inLineVolume.

**Comment by killer069** [comment]
Thanks, I got my reply for re-review.

**Comment by killer069** [comment]
Let's see how much time will it take to merge

**Comment by FHGDev** [comment]
can you merge this? it would be very helpful

**Comment by killer069** [comment]
> can you merge this? it would be very helpful

I am going to make another pull request soon. So wait till then.

**Pull request closed without merging**
