### PR TITLE
fix(esm): resolve esm imports

### LINKED ISSUE #227: Doesn't find libraries when using ES modules
### Issue description

What the title says. When using ES modules, this package can't seem to find the supporting libraries.

i.e.

```
Discord.js client is ready!
--------------------------------------------------
Core Dependencies
- @discordjs/voice: 0.7.2
- prism-media: not found

Opus Libraries
- @discordjs/opus: not found
- opusscript: not found

Encryption Libraries
- sodium: not found
- libsodium-wrappers: not found
- tweetnacl: not found

FFmpeg
- version: 4.4
- libopus: yes
--------------------------------------------------
```

even though `@discordjs/opus` is installed.

See [repro](https://github.com/codetheweb/discordjs-voice-es-bug).

### Code sample

_No response_

### @discordjs/voice version

0.7.2

### Node.js version

v16.6.1, TS 4.4.4

### Operating system

macOS

### Priority this issue should have

Medium (should be fixed soon)

### PR DESCRIPTION
**Pull request by oceanroleplay**
**Please describe the changes this PR makes and why it should be merged:**

fixes #227

### CODE REVIEW

**Comment by oceanroleplay** [comment]
Request for workflow approval, it is fixed now.

image

**Comment by oceanroleplay** [comment]
image

lib detected, hence issue will be fixed (tested). Just wait for final commit.

**Comment by oceanroleplay** [comment]
> image
> 
> lib detected, hence issue will be fixed (tested). Just wait for final commit.

ready 👍

**Comment by iCrawl** [comment]
Thanks!

I was about to do this myself but haven't had the time yet after I asked for the banner option to be added to `tsup` 👍

**Review by iCrawl — APPROVED** [review]

**Pull request merged**
