### PR TITLE
Fix for example-bot’s play command errors.

### PR DESCRIPTION
**Pull request by muhitrhn**
Updated `defer()` => `deferReply()` and changed `reply()` => `editReply` in play command.

### CODE REVIEW

**Comment by amishshah** [comment]
Duplicate of #174

**Comment by muhitrhn** [comment]
#174 doesn’t include the fix for `editReply()` part though.

**Comment by amishshah** [comment]
It comes under updating examples for v13 though, so could you either add to that PR or add it as a suggestion there instead?

**Comment by muhitrhn** [comment]
Oh hmm, okay.

**Pull request closed without merging**
